version: '3'

services:
  auth:
    build: .
    depends_on:
      - db
    container_name: auth-service
    ports:
      - 8001:8001
    environment:
      - TZ=Asia/Shanghai
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=auth-db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:5.7
    container_name: db-service
    environment:
      - MYSQL_DATABASE=auth-db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "33306:3306"
    command: mysqld --sql_mode=""
